package com.tnove.dao;

import java.sql.Blob;



/**
 * Feature generated by MyEclipse - Hibernate Tools
 */

public class Feature  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer width;
     private Integer height;
     private Double entropy;
     private Blob fuzzyHistogram;
     private Blob grayCumHistogram;
     private Blob grayHistogram;
     private Blob spatialHistogram;
     private Blob greyCoMatrix;
     private Blob fftPr;
     private Blob fftPg;


    // Constructors

    /** default constructor */
    public Feature() {
    }

	/** minimal constructor */
    public Feature(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public Feature(Integer id, Integer width, Integer height, Double entropy, Blob fuzzyHistogram, Blob grayCumHistogram, Blob grayHistogram, Blob spatialHistogram, Blob greyCoMatrix, Blob fftPr, Blob fftPg) {
        this.id = id;
        this.width = width;
        this.height = height;
        this.entropy = entropy;
        this.fuzzyHistogram = fuzzyHistogram;
        this.grayCumHistogram = grayCumHistogram;
        this.grayHistogram = grayHistogram;
        this.spatialHistogram = spatialHistogram;
        this.greyCoMatrix = greyCoMatrix;
        this.fftPr = fftPr;
        this.fftPg = fftPg;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getWidth() {
        return this.width;
    }
    
    public void setWidth(Integer width) {
        this.width = width;
    }

    public Integer getHeight() {
        return this.height;
    }
    
    public void setHeight(Integer height) {
        this.height = height;
    }

    public Double getEntropy() {
        return this.entropy;
    }
    
    public void setEntropy(Double entropy) {
        this.entropy = entropy;
    }

    public Blob getFuzzyHistogram() {
        return this.fuzzyHistogram;
    }
    
    public void setFuzzyHistogram(Blob fuzzyHistogram) {
        this.fuzzyHistogram = fuzzyHistogram;
    }

    public Blob getGrayCumHistogram() {
        return this.grayCumHistogram;
    }
    
    public void setGrayCumHistogram(Blob grayCumHistogram) {
        this.grayCumHistogram = grayCumHistogram;
    }

    public Blob getGrayHistogram() {
        return this.grayHistogram;
    }
    
    public void setGrayHistogram(Blob grayHistogram) {
        this.grayHistogram = grayHistogram;
    }

    public Blob getSpatialHistogram() {
        return this.spatialHistogram;
    }
    
    public void setSpatialHistogram(Blob spatialHistogram) {
        this.spatialHistogram = spatialHistogram;
    }

    public Blob getGreyCoMatrix() {
        return this.greyCoMatrix;
    }
    
    public void setGreyCoMatrix(Blob greyCoMatrix) {
        this.greyCoMatrix = greyCoMatrix;
    }
    
    public Blob getFftPr() {
        return this.fftPr;
    }
    
    public void setFftPr(Blob fftPr) {
        this.fftPr = fftPr;
    }
    
    public Blob getFftPg() {
        return this.fftPg;
    }
    
    public void setFftPg(Blob fftPg) {
        this.fftPg = fftPg;
    }
   








}