package com.tnove.dao;

import java.sql.Blob;



/**
 * Image generated by MyEclipse - Hibernate Tools
 */

public class Image  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String imageName;
     private Blob value;
     private Integer width;
     private Integer height;
     private String keyword;
     private String url;
     private String fatherUrl;


    // Constructors

    /** default constructor */
    public Image() {
    }

	/** minimal constructor */
    public Image(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public Image(Integer id, String imageName, Blob value, Integer width, Integer height, String keyword, String url, String fatherUrl) {
        this.id = id;
        this.imageName = imageName;
        this.value = value;
        this.width = width;
        this.height = height;
        this.keyword = keyword;
        this.url = url;
        this.fatherUrl = fatherUrl;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getImageName() {
        return this.imageName;
    }
    
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }

    public Blob getValue() {
        return this.value;
    }
    
    public void setValue(Blob value) {
        this.value = value;
    }

    public Integer getWidth() {
        return this.width;
    }
    
    public void setWidth(Integer width) {
        this.width = width;
    }

    public Integer getHeight() {
        return this.height;
    }
    
    public void setHeight(Integer height) {
        this.height = height;
    }

    public String getKeyword() {
        return this.keyword;
    }
    
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    public String getFatherUrl() {
        return this.fatherUrl;
    }
    
    public void setFatherUrl(String fatherUrl) {
        this.fatherUrl = fatherUrl;
    }
   








}